import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
dotenv.config();
// MiniMax M2.7 via OpenAI-compatible API (replaced Gemini)
import multer from 'multer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { createClient as createTursoClient } from '@libsql/client/web';
import { S3Client, PutObjectCommand, DeleteObjectCommand } from '@aws-sdk/client-s3';

// ES Module dirname equivalent
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3005;

app.use(cors());
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ limit: '50mb', extended: true }));

// Prevent caching for API routes
app.use('/api', (req, res, next) => {
    res.set('Cache-Control', 'no-store, no-cache, must-revalidate, private');
    next();
});

// --- In-Memory Cache ---
// Simple TTL cache to reduce redundant database reads
const cache = new Map();
const CACHE_TTL = 60000; // 60 seconds

function getCached(key) {
    const entry = cache.get(key);
    if (entry && Date.now() - entry.time < CACHE_TTL) {
        return entry.data;
    }
    cache.delete(key);
    return null;
}

function setCache(key, data) {
    cache.set(key, { data, time: Date.now() });
}

function invalidateCache(prefix) {
    for (const key of cache.keys()) {
        if (key.startsWith(prefix)) cache.delete(key);
    }
}

// --- Middleware: Authentication ---
// Simple token-based auth (for now, checks for presence of token or mock-token)
// In production, verify JWT properly.
const authenticateToken = (req, res, next) => {
    const authHeader = req.headers['authorization'];
    const token = authHeader && authHeader.split(' ')[1];

    if (token == null) return res.sendStatus(401); // No token

    // For this stage, we accept the mock token generated by login
    // Or a real JWT if implemented later.
    // Allow if verified or if it matches our mock pattern
    if (token.startsWith('mock-token-')) {
        next();
    } else {
        return res.sendStatus(403); // Invalid token
    }
};

// --- Middleware: Admin Check ---
// Checks if the user role is admin (requires fetching user from DB based on token normally)
// For now, we'll assume any authenticated user can access (or implement basic role check if payload existed)


// Initialize Cloudflare R2 Client (for gallery image storage)
const r2 = new S3Client({
    region: 'auto',
    endpoint: process.env.R2_ENDPOINT,
    credentials: {
        accessKeyId: process.env.R2_ACCESS_KEY_ID,
        secretAccessKey: process.env.R2_SECRET_ACCESS_KEY,
    },
});
const R2_BUCKET = 'anniks-gallery';
const R2_PUBLIC_URL = process.env.R2_PUBLIC_URL;

// Configure multer for memory storage (buffer) to upload to R2
const galleryStorage = multer.memoryStorage();

const galleryUpload = multer({
    storage: galleryStorage,
    limits: { fileSize: 10 * 1024 * 1024 }, // 10MB limit
    fileFilter: (req, file, cb) => {
        const allowedTypes = ['image/jpeg', 'image/png', 'image/webp', 'image/gif'];
        if (allowedTypes.includes(file.mimetype)) {
            cb(null, true);
        } else {
            cb(new Error('Only JPEG, PNG, WebP, and GIF images are allowed'));
        }
    }
});

const geminiApiKey = process.env.VITE_GEMINI_API_KEY;
const minimaxApiKey = process.env.MINIMAX_API_KEY;

// --- AI Provider Functions ---

async function callGemini(apiKey, model, systemPrompt, userPrompt, temperature) {
    const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`,
        {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                system_instruction: { parts: [{ text: systemPrompt }] },
                contents: [{ parts: [{ text: userPrompt }] }],
                generationConfig: { temperature, maxOutputTokens: 500 }
            })
        }
    );

    if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        const msg = err.error?.message || `HTTP ${response.status}`;
        throw new Error(`Gemini error: ${msg}`);
    }

    const data = await response.json();
    let text = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
    // Clean up JSON wrapper if present
    text = text.replace(/^```json\s*/, '').replace(/\s*```$/, '');
    try { text = JSON.parse(text); } catch {}
    return text;
}

async function callMiniMax(apiKey, model, systemPrompt, userPrompt, temperature) {
    const response = await fetch('https://api.minimax.io/v1/chat/completions', {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${apiKey}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            model,
            messages: [
                { role: 'system', content: systemPrompt },
                { role: 'user', content: userPrompt }
            ],
            temperature,
            max_completion_tokens: 500
        })
    });

    if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        throw new Error(`MiniMax API error ${response.status}: ${err.error?.message || 'Unknown'}`);
    }

    const data = await response.json();
    let text = data.choices?.[0]?.message?.content || '';
    // Strip <think>...</think> reasoning tags
    text = text.replace(/<think>[\s\S]*?<\/think>/g, '').trim();
    return text;
}

// Primary: Gemini Flash Lite (0.86s, no reasoning overhead)
// Fallback: MiniMax M2.7-highspeed (1.2s) if Gemini fails
async function generateDraft(systemPrompt, userPrompt, temperature) {
    // Try Gemini Flash Lite first
    if (geminiApiKey) {
        try {
            return await callGemini(geminiApiKey, 'gemini-2.5-flash-lite', systemPrompt, userPrompt, temperature);
        } catch (err) {
            console.warn('[generate] Gemini failed, falling back to MiniMax:', err.message);
        }
    }
    // Fallback to MiniMax highspeed
    if (minimaxApiKey) {
        return await callMiniMax(minimaxApiKey, 'gemini-2.5-flash-lite-highspeed', systemPrompt, userPrompt, temperature);
    }
    throw new Error('No AI provider available');
}

// --- Customer Persona Pool ---
// Each persona gives the AI a unique life situation to write from.
// On each generation, 3 are randomly selected (Fisher-Yates) so every draft sounds like a different person.
const CUSTOMER_PERSONAS = [
    // --- Office & Work Life ---
    "30s office worker, sits 10 hours a day. Back and neck always aching, posture getting worse. Colleague told her about this place.",
    "Stressed from work deadlines, jaw clenching at night, tension headaches every week. Needs a physical reset, not just mental.",
    "Remote worker who's been WFH for 3 years. Rounded shoulders and tech neck from the laptop setup. Finally doing something about it.",
    "Corporate lawyer, always in heels and sitting in meetings. Lower back pain became unbearable. Colleague's posture visibly changed after coming here.",
    "Teacher who stands all day. Knee and hip pain from bad alignment. Physiotherapy helped temporarily but nothing stuck.",

    // --- Moms & Family ---
    "Mom of two toddlers, finally carved out 'me time'. Husband watching the kids so she can have this one session.",
    "Brought her mother here for posture correction. Mom was reluctant at first but loved it. Reviewing on mom's behalf.",
    "40s professional, body shape shifted after pregnancy. Looking for something gentle that actually works, not extreme.",
    "New mom, 4 months postpartum. Body doesn't feel like hers anymore. Wants gentle recovery, not gym bootcamp.",
    "Daughter bought this as a Mother's Day gift for her mom. Mom was skeptical but came out smiling.",
    "Pregnant friend recommended this for postpartum recovery. Finally came 6 months after giving birth.",

    // --- Social Discovery ---
    "Came with her bestie who's been coming for months. Was skeptical but her friend's jawline change was undeniable.",
    "Colleague's face literally changed after a few sessions. Had to find out what this place actually does.",
    "Saw Anniks on XHS/小红书, the before-after photos looked real (not filtered) so decided to try.",
    "Husband noticed her sister's face looked different at a family dinner. Sister spilled the secret, so she booked immediately.",
    "Gym buddy told her about a place that fixed her pelvic tilt without exercise. Had to try it herself.",
    "Overheard two ladies at a cafe raving about their face sculpting results. Googled it on the spot.",

    // --- Life Events & Milestones ---
    "Getting married in 2 months. Wants face shape and posture to look perfect in the wedding photos.",
    "Birthday treat to herself. Turning 30 and investing in how she feels, not just how she looks.",
    "Just went through a breakup. Treating herself as part of her 'glow up era'. Wants to feel confident again.",
    "Graduating university next month. Wants to look sharp and feel great for the convocation photos.",
    "Company annual dinner coming up. Wants to look her best in the evening dress without Photoshop.",

    // --- Pain & Skepticism ---
    "Scared of pain. Tried bone-setting (跌打) before and it was traumatic. Very cautious this time.",
    "Tried chiropractor, traditional massage, and yoga for her posture. Nothing stuck long-term. Last resort.",
    "Auntie who's done every facial and body treatment in KL. Hard to impress, very picky.",
    "Boyfriend thinks beauty treatments are a scam. Came secretly to prove him wrong with visible results.",
    "Has been living with an asymmetric jaw for years. Dentist said it's muscular, not dental. Looking for alternatives.",

    // --- Loyal & Returning ---
    "Loyal client, 5th visit. Jawline already changed, here for posture correction this time.",
    "Second visit. First time was so good she bought a package. Here to continue the progress.",
    "Been coming monthly for 6 months. Friends keep asking what she's doing differently. She just smiles.",

    // --- Seasonal & Situational ---
    "Post-CNY recovery. Face puffy, body stiff from too much eating and sitting around for 2 weeks.",
    "Just came back from a long-haul flight. Jet lag plus sitting for 12 hours destroyed her posture.",
    "Raya is around the corner. Wants to look good in baju kurung without sucking in her stomach.",
    "Year-end holiday treat. Used up her remaining annual leave to pamper herself before the new year.",

    // --- Fitness & Active Lifestyle ---
    "Fitness girl who works out 5x a week but can't fix her anterior pelvic tilt on her own.",
    "Yoga instructor who noticed her own alignment was off. Came to get professionally assessed.",
    "Marathon runner with recurring hip pain. Physio said her pelvis is tilted. Trying a different approach.",

    // --- Unique Demographics ---
    "University student, saved up from part-time job to try this. First time doing anything like this.",
    "Expat living in KL for 2 years. Tried many wellness places but most were just spa-level. Looking for real results.",
    "Flight attendant with chronic neck and shoulder issues from pulling luggage and standing in heels. Irregular schedule makes regular treatment hard."
];

const PROMPTS_SYSTEM_INSTRUCTION = `
You are writing as a REAL CUSTOMER, not a brand, not a marketer, not an influencer.
Write reviews for "Anniks Beauty", a body sculpting, posture correction & wellness studio in Malaysia (branches in Cheras & Penang). Founded in 2019, they advocate "养生年轻化" (wellness for the younger generation, prevention over cure).
Sound like a real person posting on social media — not an ad, not a brochure.

You will be given a customer persona. Write from their perspective — let their life situation, motivations, and personality shape the review naturally. Do NOT state the persona details literally. Let them color your word choice, what you notice, and how you feel about the experience.

Key context about Anniks Beauty:
- Pain-free, non-invasive treatments (they use the gentlest approach and adjust to each client's tolerance)
- Their signature 3-step method: muscle relaxation, bone realignment, muscle training
- "做一次看见效果，3次调理，5次定型" (see results in 1 session, 3 sessions to adjust, 5 to set)
- Malaysia's first wellness studio combining body and mind healing
- 95% customer referral rate, certified therapists
- Services include: facial contouring, jawline shaping, V-line sculpting, nose lifting, posture correction, pelvic repair, breast care, and women's intimate health

Core principles:
- First person, casual, warm. Write how Malaysians actually type.
- Pick 1-2 details from what the customer chose — do NOT exhaustively list everything.
- Do NOT keep repeating "Anniks Beauty" in the review. Real customers don't name-drop the brand multiple times. Mention it at most ONCE, and only if it feels natural (e.g., "went to Anniks" or "tried Anniks"). On Google/Facebook the brand name is already on the page — the review doesn't need to spell it out again.
- NEVER quote service names verbatim. Real customers don't say "I did the Facial Contour Refinement" or "Posture Sculpting Therapy". They say things like "did their face sculpting", "went for a body alignment session", "tried their jawline thing", "went for posture correction". Paraphrase naturally how a real person would describe it.
- SENSITIVE SERVICES: For intimate/private services (breast care, uterine health, vaginal tightening, organs rejuvenation, women's intimate health), NEVER use clinical or explicit terms in the review. Use discreet language like "women's wellness treatment", "intimate health session", "private care", "women's health therapy", "body wellness treatment". Real women do not publicly write words like "vagina", "uterine", or "breast firming" in social media reviews. Keep it tasteful and vague.
- Never use marketing phrases ("state-of-the-art", "luxurious", "top-notch", "highly recommend to everyone").
- Never use "—" (em dash).
- If rating is 1-3: honest disappointment. If 4-5: genuinely happy.
- Use emojis on Facebook/Instagram/XHS. Google: 1-2 max.

BEFORE-STATE CONTRAST: When expressing a highlight, establish a relatable BEFORE state first, then show the contrast. This creates a mini story arc:
- "Friendly Staff" -> mention being nervous or unsure walking in, then how staff put you at ease
- "Clean Environment" -> mention having been to dodgy/average places before, or not expecting much from a wellness studio
- "Professional Therapists" -> mention not understanding your own body issues, then how the therapist explained and educated you
- "Visible Results" -> mention living with the problem (crooked jaw, bad posture, puffy face), then the visible change after
- "Pain-Free" -> mention dreading it based on past experiences (chiropractor, bone-setting), then how surprisingly gentle it was
- "Good Value" -> mention expecting it to cost more for this level of treatment, or comparing to pricier clinics
- "Holistic Approach" -> mention going to places that only fix one thing, then how Anniks looked at the whole picture
- "Body & Mind Wellness" -> mention feeling physically and mentally drained before, then the combined relief after

MICRO-DETAILS: Sprinkle in ONE small sensory or experiential detail to ground the review in reality. Pick only ONE per review:
- Physical: "the muscle relaxation part was so soothing", "felt my jaw click into place gently", "the bone realignment step was oddly satisfying", "my shoulders dropped like 2 inches during the session"
- Environment: "the treatment room was so quiet and calming", "the whole place smelled clean, not perfume-y", "the lighting was soft, very relaxing", "the consultation area had a full-length mirror so you can see before/after"
- After-effects: "kept checking my jawline in every mirror I passed", "my colleague asked if I lost weight (it was just better posture)", "husband said my face looked different", "took a selfie right after and my face shape actually changed", "posture was still noticeably better the next morning"
- Little touches: "they showed me my posture analysis on screen", "no hard sell at the end which I really appreciated", "she explained exactly what she was doing at each step", "they took before and after photos so I could compare"

Platform style:
- Google: 2-4 sentences, informative but warm. NO hashtags.
- Facebook: Casual and conversational, like telling a friend. NOT excited/hype like XHS. Light emojis ok. NO hashtags.
- Instagram: Short caption vibes. NO hashtags.
- XHS (小红书): Story-style, enthusiastic discovery feel, 姐妹们 tone ok here. MUST end with hashtags: #无痛变美 #体态矫正 #骨盆修复 #小颜术 #身心疗愈

When the customer selects a highlight, express it in a DIFFERENT way each time. Never repeat the same phrasing. Examples:
- "Friendly Staff" → "she was really sweet", "the girl at the counter made me feel at ease", "staff were so patient with all my questions", "everyone there was super nice", "they really took care of me", "felt welcomed from the moment I walked in", "the team was warm and attentive", "no pressure at all, very chill staff", "loved how friendly everyone was", "they made the whole experience comfortable"
- "Clean Environment" → "the place was spotless", "everything looked so clean and well-kept", "loved how neat the treatment room was", "hygiene level was A+", "the space felt fresh and calming", "super clean, you can tell they take it seriously", "the whole place smelled nice and looked pristine", "treatment room was immaculate", "very well-maintained space", "cleanliness was on point"
- "Professional Therapists" → "the therapist really knew what she was doing", "she explained every step clearly", "you can tell they're properly trained", "the consultation was thorough and professional", "she assessed my posture and explained exactly what needed correcting", "felt like I was in expert hands", "the therapist was certified and really knowledgeable", "she broke down the whole process for me", "they didn't just do the treatment, they educated me on how to maintain it", "the professionalism was next level"
- "Visible Results" → "saw the difference right after one session", "my posture looked completely different in the mirror", "the before and after was crazy", "couldn't believe the change after just one visit", "my jawline was visibly sharper immediately", "friends noticed the difference the same day", "the results were instant and real", "I could literally see my face shape change", "one session and my body alignment improved so much", "the transformation was visible straightaway"
- "Pain-Free" → "honestly didn't feel any pain at all", "was so surprised how gentle it was", "I was dreading it but it was completely painless", "way more comfortable than I expected", "no pain, just a really soothing session", "they adjusted the pressure to my comfort level", "I'm someone who's scared of pain but this was totally fine", "the whole thing was so gentle I almost fell asleep", "nothing like those painful bone-cracking places", "they really live up to the pain-free promise"
- "Good Value" → "great price for what you get", "honestly didn't expect this quality at that price", "worth every sen", "way more value than I expected", "you get a lot for the money", "compared to other places this is a steal", "the results you get for the price is impressive", "really reasonable for the quality", "I'd pay more honestly, it was that good", "best bang for your buck"
- "Holistic Approach" → "they don't just fix one area, they look at your whole body", "loved how they addressed the root cause not just symptoms", "the 3-step approach really makes sense", "they explained how everything is connected", "it's not just about looking good, they care about your overall health", "the whole-body approach is what sets them apart", "they treated my posture issue by looking at everything from my spine to my pelvis", "finally a place that doesn't just do surface-level fixes", "they combine physical correction with wellness which is so rare", "the holistic method gave me way better results than targeted treatments elsewhere"
- "Body & Mind Wellness" → "left feeling physically and mentally refreshed", "it's not just body work, they take care of your mental state too", "the session was like therapy for my body and mind", "I felt so much lighter emotionally after", "they combine wellness with beauty in a way I haven't seen before", "the whole experience was healing on every level", "came for body sculpting but left with inner peace too", "Malaysia's first body and mind wellness combo and I can see why", "the mind-body connection they create is special", "it's wellness in the truest sense"

Examples of good reviews:

[Google, EN, 5★]
Been dealing with bad desk posture for years, finally tried the Posture Sculpting here. Callie explained every step and honestly my shoulders feel like they dropped two inches 😊 Will def be back.

[Google, EN, 2★]
Came in for posture correction. Results were okay but nothing dramatic. Had to wait quite a while too. Might give it another shot but expected more for the price.

[Facebook, EN, 5★]
Tried the V Line Sculpting today and honestly really happy with how my face looked after. The therapist was patient and explained the whole 3-step process. My colleague saw me after and asked if I lost weight lol. Would go again 😊

[Instagram, EN, 5★]
that post-session glow tho ✨ jawline looking sharper after one visit 🌿

[Google, BM, 5★]
Baru try Posture Sculpting sini. Badan rasa lega gila lepas tu, postur pun nampak lain 😊 Florence sangat gentle, explain semua step. Memang puas hati.

[XHS, CN, 5★]
姐妹们！今天去做了美骨小颜术 🌿 之前下巴线条一直很模糊，做完脸型真的变小了～完全不痛，差点睡着哈哈 回去路上一直照镜子 推荐给想变美又怕痛的姐妹！#无痛变美 #体态矫正 #小颜术 #身心疗愈

[Google, CN, 4★]
第一次来做体态塑形，感觉还不错。坐办公室太久体态一直不好，做完确实有改善，Annika手法很轻柔 😊

[Facebook, BM, 5★]
Buat Jawline Shaping tadi. Lepas treatment muka memang nampak lain, lebih kecil. Tempat dia bersih dan terapis pun friendly. Berbaloi la 👍

Return ONLY the review text. No explanations.
`;

// Placeholder - will be replaced after db is initialized
const getAiConfig = async () => {
    try {
        if (!pool) return null;
        const res = await pool.query('SELECT * FROM ai_config LIMIT 1');
        return res.rows[0] || null;
    } catch (err) {
        console.error("Error fetching AI config:", err);
        return null;
    }
};

app.post('/api/generate-reviews', async (req, res) => {
    try {
        if (!geminiApiKey && !minimaxApiKey) {
            return res.status(500).json({ error: "No AI API keys configured" });
        }

        const { platform, services, highlights, staffName, therapistName, rating, tone, length, language } = req.body;

        // Fetch AI config from database
        const aiConfig = await getAiConfig();

        // Use database config or fallback to hardcoded defaults
        const systemPrompt = aiConfig?.system_prompt || PROMPTS_SYSTEM_INSTRUCTION;
        const temperature = aiConfig?.temperature ?? 0.95;

        // Fetch knowledgebase entries that match the selected services
        const knowledgeEntries = await getKnowledgeForServices(services);
        let knowledgeContext = '';
        if (knowledgeEntries.length > 0) {
            knowledgeContext = '\nBackground info (weave in naturally only if relevant):\n' +
                knowledgeEntries.map(entry => `- ${entry.title}: ${entry.content}`).join('\n');
        }

        // Build scenario context
        const servicesStr = services?.join(", ") || "a facial treatment";
        const highlightsStr = highlights?.length > 0 ? highlights.join("; ") : "";
        const staffStr = staffName && staffName !== 'not_sure' ? staffName : "";
        const therapistStr = therapistName && therapistName !== 'not_sure' ? therapistName : "";
        const langInstruction = language ? `Write in ${language}.` : "";
        const lengthGuide = length === 'Short' ? "STRICTLY 1-2 sentences only. Keep it brief and punchy — no more." : length === 'Medium' ? "3-4 sentences, conversational flow." : "6-8 sentences with storytelling — describe the visit, treatment, and how you felt after in detail.";
        const ratingGuide = rating <= 3 ? "The customer was disappointed — write an honest, measured review reflecting that." : "The customer loved it — write a genuinely happy review.";

        // Platform-specific style enforcement (injected into each draft prompt)
        const platformStyles = {
            'Google': 'STYLE: Google Review. 2-4 sentences, informative but warm. NO hashtags. NO emojis except 1-2 max. Write like a real Google review - calm, helpful, factual with a personal touch. NOT excited, NOT hype.',
            'Facebook': 'STYLE: Facebook post. Casual and conversational, like telling a friend about your day. Light emojis ok. NO hashtags. NOT excited/hype like XHS. Do NOT use "姐妹们". Write like a normal Facebook status update - relaxed, personal, grounded.',
            'Instagram': 'STYLE: Instagram caption. Short, visual, caption vibes. NO hashtags. Keep it aesthetic and brief.',
            'XHS': 'STYLE: 小红书 post. Story-style, enthusiastic discovery feel. 姐妹们 tone ok here. MUST end with hashtags: #无痛变美 #体态矫正 #骨盆修复 #小颜术 #身心疗愈',
            'TikTok': 'STYLE: TikTok caption. Short, punchy, trendy. Casual Gen-Z tone.'
        };
        const platformStyle = platformStyles[platform] || `STYLE: ${platform} post. Write naturally for this platform.`;

        // Per-draft persona angles for variation
        const draftAngles = [
            { angle: "SENSORY FOCUS", instruction: "Focus on how the treatment physically felt — textures, sensations, touch, comfort during the session." },
            { angle: "OUTCOME FOCUS", instruction: "Focus on the results — what changed, how skin looked/felt after, whether it was worth it." },
            { angle: "ATMOSPHERE FOCUS", instruction: "Focus on the vibe — people, environment, comfort, little details that made the visit memorable." }
        ];

        // Therapist mention modes - shuffled so each draft handles it differently
        // Real reviews: some name the therapist, some say "the therapist/she", some don't mention anyone
        const therapistModes = ['named', 'anonymous', 'omitted'];
        for (let i = therapistModes.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [therapistModes[i], therapistModes[j]] = [therapistModes[j], therapistModes[i]];
        }

        // Fisher-Yates shuffle to pick 3 unique personas
        const shuffled = [...CUSTOMER_PERSONAS];
        for (let i = shuffled.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
        }
        const selectedPersonas = shuffled.slice(0, 3);

        // Make 3 parallel API calls, each with its own scenario
        // Primary: Gemini Flash Lite (~0.9s) | Fallback: MiniMax-highspeed (~1.2s)
        const draftPromises = draftAngles.map(({ angle, instruction }, index) => {
            const persona = selectedPersonas[index];

            // Per-draft therapist line
            let therapistLine = '';
            if (therapistStr) {
                const mode = therapistModes[index];
                if (mode === 'named') {
                    therapistLine = `- Therapist: ${therapistStr}`;
                } else if (mode === 'anonymous') {
                    therapistLine = `- A therapist helped you but do NOT use any name. Say "the therapist" or "she".`;
                }
            }

            // Build full scenario per draft
            const scenario = [
                `A customer just visited Anniks Beauty and had: ${servicesStr}.`,
                `Platform: ${platform}. ${langInstruction}`,
                platformStyle,
                `Rating: ${rating}/5. ${ratingGuide}`,
                `Tone: ${tone}. Length: ${lengthGuide}`,
                '',
                highlightsStr ? `- Customer felt: ${highlightsStr}` : '',
                staffStr ? `- Helped by: ${staffStr}` : '',
                therapistLine,
                knowledgeContext,
            ].filter(Boolean).join('\n');

            const prompt = `[${angle}]: ${instruction}\nYou are: ${persona}. Let this shape your story naturally.\n\n${scenario}\n\nReturn ONLY the review text. Nothing else.`;
            return generateDraft(systemPrompt, prompt, temperature);
        });

        let drafts = await Promise.all(draftPromises);

        // Filter out empty drafts (MiniMax occasionally returns empty)
        drafts = drafts.filter(d => d && d.trim() !== '');

        res.json({ drafts });

    } catch (error) {
        console.error("Server AI Error:", error);
        res.status(500).json({ error: error.message });
    }
});

// --- Database Setup (Turso/libSQL) ---
const turso = createTursoClient({
    url: process.env.TURSO_DATABASE_URL,
    authToken: process.env.TURSO_AUTH_TOKEN
});

// Compatibility layer: converts pg-style $1,$2 params to ? for libSQL
const pool = {
    query: async (sql, params = []) => {
        const convertedSql = sql.replace(/\$\d+/g, '?');
        const result = await turso.execute({
            sql: convertedSql,
            args: params
        });
        return {
            rows: result.rows,
            rowCount: result.rowsAffected
        };
    }
};

console.log('Turso database client initialized.');

// Initialize Tables
const initDB = async () => {
    try {
        await pool.query(`
    CREATE TABLE IF NOT EXISTS submissions (
      id TEXT PRIMARY KEY,
      customerName TEXT,
      branchId TEXT,
      staffId TEXT,
      therapistId TEXT,
      products TEXT, -- JSON
      highlights TEXT, -- JSON
      rating INTEGER,
      feedback TEXT,
      platformsSelected TEXT, -- JSON
      proofs TEXT, -- JSON
      status TEXT,
      timestamp BIGINT,
      rewardClaimed INTEGER,
      luckyDrawTicket TEXT,
      phone TEXT,
      bonusEntries INTEGER
    )`);

        await pool.query(`
    CREATE TABLE IF NOT EXISTS visits (
      id TEXT PRIMARY KEY,
      branchId TEXT,
      timestamp BIGINT
    )`);

        await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      username TEXT UNIQUE,
      password TEXT, -- In production, use bcrypt. For demo, plain text/simple hash.
      role TEXT,
      profile_pic TEXT
    )`);

        // Seed Default Admin if not exists
        const adminCheck = await pool.query("SELECT * FROM users WHERE username = 'admin'");
        if (adminCheck.rows.length === 0) {
            await pool.query("INSERT INTO users (id, username, password, role) VALUES ($1, $2, $3, $4)", ['admin-1', 'admin', 'admin123', 'admin']);
            console.log("Seeded default admin user.");
        }

        // Mystery Gifts table
        await pool.query(`
    CREATE TABLE IF NOT EXISTS mystery_gifts (
      id TEXT PRIMARY KEY,
      name TEXT,
      image TEXT,
      stock INTEGER DEFAULT 0,
      threshold INTEGER DEFAULT 5,
      given_out INTEGER DEFAULT 0,
      created_at TEXT
    )`);

        // Seed Default Mystery Gift if not exists
        const giftCheck = await pool.query("SELECT * FROM mystery_gifts LIMIT 1");
        if (giftCheck.rows.length === 0) {
            await pool.query("INSERT INTO mystery_gifts (id, name, image, stock, threshold, given_out, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7)",
                ['gift-1', 'Mystery Gift Box', null, 10, 3, 0, new Date().toISOString()]);
            console.log("Seeded default mystery gift.");
        }

        // AI Configuration table
        await pool.query(`
    CREATE TABLE IF NOT EXISTS ai_config (
      id TEXT PRIMARY KEY DEFAULT 'default',
      model_name TEXT DEFAULT 'gemini-2.5-flash-lite',
      system_prompt TEXT,
      selling_points TEXT,
      temperature REAL DEFAULT 0.7,
      updated_at TEXT
    )`);

        // Seed Default AI Config if not exists
        const defaultSystemPrompt = PROMPTS_SYSTEM_INSTRUCTION;

        const defaultSellingPoints = JSON.stringify([]);

        const aiConfigCheck = await pool.query("SELECT * FROM ai_config WHERE id = 'default'");
        if (aiConfigCheck.rows.length === 0) {
            await pool.query("INSERT INTO ai_config (id, model_name, system_prompt, selling_points, temperature, updated_at) VALUES ($1, $2, $3, $4, $5, $6)",
                ['default', 'gemini-2.5-flash-lite', defaultSystemPrompt, defaultSellingPoints, 0.95, new Date().toISOString()]);
            console.log("Seeded default AI configuration.");
        } else {
            // Always sync model name + system prompt from code to DB on startup
            await pool.query("UPDATE ai_config SET model_name = $1, system_prompt = $2, updated_at = $3 WHERE id = 'default'",
                ['gemini-2.5-flash-lite', defaultSystemPrompt, new Date().toISOString()]);
            console.log("Synced model name and system prompt to database.");
        }

        // Knowledgebase table
        await pool.query(`
    CREATE TABLE IF NOT EXISTS knowledgebase (
      id TEXT PRIMARY KEY,
      category TEXT DEFAULT 'general',
      title TEXT NOT NULL,
      content TEXT,
      tags TEXT,
      created_at TEXT,
      updated_at TEXT
    )`);

        // Gallery Images table
        await pool.query(`
    CREATE TABLE IF NOT EXISTS gallery_images (
      id TEXT PRIMARY KEY,
      filename TEXT NOT NULL,
      original_name TEXT,
      category TEXT DEFAULT 'general',
      tags TEXT,
      use_count INTEGER DEFAULT 0,
      created_at TEXT,
      url TEXT
    )`);

        // Migration: Add url column if it doesn't exist
        try {
            await pool.query("ALTER TABLE gallery_images ADD COLUMN url TEXT");
        } catch (e) {
            console.log("Migration note: url column already exists or error ignored");
        }

        // Gallery Settings table
        await pool.query(`
    CREATE TABLE IF NOT EXISTS gallery_settings (
      id TEXT PRIMARY KEY,
      allow_multiple_uses INTEGER DEFAULT 0,
      updated_at TEXT
    )`);

        // Seed default gallery settings
        await pool.query(`INSERT INTO gallery_settings (id, allow_multiple_uses, updated_at) VALUES ('default', 0, datetime('now')) ON CONFLICT (id) DO NOTHING`);

        // Branches table
        await pool.query(`
        CREATE TABLE IF NOT EXISTS branches (
            id TEXT PRIMARY KEY,
            name TEXT
        )`);

        // Seed default branches
        await pool.query(`INSERT INTO branches (id, name) VALUES ('b1', 'Cheras') ON CONFLICT (id) DO NOTHING`);
        await pool.query(`INSERT INTO branches (id, name) VALUES ('b2', 'Penang') ON CONFLICT (id) DO NOTHING`);

        // Staff table
        await pool.query(`
        CREATE TABLE IF NOT EXISTS staff (
            id TEXT PRIMARY KEY,
            name TEXT,
            role TEXT, -- 'staff' or 'therapist'
            branch_id TEXT
        )`);

        // Seed default staff (therapists per branch)
        const staffCount = (await pool.query('SELECT COUNT(*) FROM staff')).rows[0].count;
        if (parseInt(staffCount) === 0) {
            await pool.query(`
                INSERT INTO staff (id, name, role, branch_id) VALUES
                ('t1', 'Annika', 'therapist', 'b1'),
                ('t2', 'Callie', 'therapist', 'b1'),
                ('t3', 'Florence', 'therapist', 'b1'),
                ('t4', 'Tracy', 'therapist', 'b1'),
                ('t5', 'Victoria', 'therapist', 'b2'),
                ('t6', 'Callie', 'therapist', 'b2'),
                ('t7', 'Jolin', 'therapist', 'b2')
            `);
        }

    } catch (err) {
        console.error("Error initializing DB:", err);
    }
};

initDB().catch(err => console.error('[initDB] Unhandled error:', err));

// Now that db is initialized, set up the real getAiConfig function
// getAiConfig is now defined at the top level and uses the pool directly.

// Helper function to get knowledge entries matching services
// Helper function to get knowledge entries matching services
const getKnowledgeForServices = async (services) => {
    try {
        const result = await pool.query("SELECT * FROM knowledgebase");
        const rows = result.rows;

        if (!rows || rows.length === 0) {
            return [];
        }

        // Match entries based on service names or tags
        const matchedEntries = rows.filter(entry => {
            const entryTitle = entry.title?.toLowerCase() || '';
            const entryTags = (() => {
                try {
                    return JSON.parse(entry.tags || '[]').map(t => t.toLowerCase());
                } catch {
                    return [];
                }
            })();

            // Check if any service matches this entry
            return services?.some(service => {
                const serviceLower = service.toLowerCase();
                return entryTitle.includes(serviceLower) ||
                    serviceLower.includes(entryTitle) ||
                    entryTags.some(tag => serviceLower.includes(tag) || tag.includes(serviceLower));
            });
        });

        console.log(`📚 Found ${matchedEntries.length} knowledge entries for services:`, services);
        return matchedEntries;
    } catch (err) {
        console.error("Error fetching knowledgebase:", err);
        return [];
    }
};

// --- API Routes for Mystery Gifts ---

// Get all mystery gifts
// --- API Routes for Mystery Gifts ---

// Get all mystery gifts (cached)
app.get('/api/mystery-gifts', async (req, res) => {
    try {
        const cached = getCached('mystery-gifts');
        if (cached) return res.json(cached);

        const result = await pool.query("SELECT * FROM mystery_gifts ORDER BY created_at DESC");
        const data = result.rows || [];
        setCache('mystery-gifts', data);
        res.json(data);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Create a new mystery gift
app.post('/api/mystery-gifts', authenticateToken, async (req, res) => {
    const { name, image, stock, threshold } = req.body;
    const id = 'gift-' + Date.now();
    const created_at = new Date().toISOString();

    try {
        await pool.query(
            "INSERT INTO mystery_gifts (id, name, image, stock, threshold, given_out, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7)",
            [id, name, image, stock || 0, threshold || 5, 0, created_at]
        );
        invalidateCache('mystery-gifts');
        res.json({ success: true, id, name, image, stock: stock || 0, threshold: threshold || 5, given_out: 0, created_at });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Update a mystery gift
// Update a mystery gift
app.put('/api/mystery-gifts/:id', authenticateToken, async (req, res) => {
    const { id } = req.params;
    const { name, image, stock, threshold } = req.body;

    const updates = [];
    const values = [];
    let idx = 1;

    if (name !== undefined) { updates.push(`name = $${idx++}`); values.push(name); }
    if (image !== undefined) { updates.push(`image = $${idx++}`); values.push(image); }
    if (stock !== undefined) { updates.push(`stock = $${idx++}`); values.push(stock); }
    if (threshold !== undefined) { updates.push(`threshold = $${idx++}`); values.push(threshold); }

    if (updates.length === 0) {
        return res.status(400).json({ error: 'No valid fields to update' });
    }

    values.push(id);
    const query = `UPDATE mystery_gifts SET ${updates.join(', ')} WHERE id = $${idx}`;

    try {
        const result = await pool.query(query, values);
        invalidateCache('mystery-gifts');
        res.json({ success: true, updated: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Delete a mystery gift
// Delete a mystery gift
app.delete('/api/mystery-gifts/:id', authenticateToken, async (req, res) => {
    const { id } = req.params;
    try {
        const result = await pool.query("DELETE FROM mystery_gifts WHERE id = $1", [id]);
        invalidateCache('mystery-gifts');
        res.json({ success: true, deleted: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Deduct stock (called when review is verified) - Public or Protected?
// Usually called by server internally or protected. But let's leave public for now as customer flow triggers it via backend logic?
// No, customer flow calls verify, which might trigger this. 
// Wait, customer flow calls `addSubmission`. Where is deduct called? 
// It is not called in current code! It's a standalone endpoint. 
// Let's assume valid verification logic calls it. Protected.
app.post('/api/mystery-gifts/deduct', authenticateToken, async (req, res) => {
    try {
        // Find the first gift with stock > 0
        const result = await pool.query("SELECT * FROM mystery_gifts WHERE stock > 0 ORDER BY created_at ASC LIMIT 1");
        const gift = result.rows[0];

        if (!gift) return res.json({ success: false, message: 'No gifts in stock' });

        await pool.query("UPDATE mystery_gifts SET stock = stock - 1, given_out = given_out + 1 WHERE id = $1", [gift.id]);
        invalidateCache('mystery-gifts');
        res.json({ success: true, gift_id: gift.id, gift_name: gift.name, new_stock: gift.stock - 1 });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// --- API Routes for Dashboard ---

// --- API Routes for AI Configuration ---

// Get AI config (cached)
app.get('/api/ai-config', async (req, res) => {
    try {
        const cached = getCached('ai-config');
        if (cached) return res.json(cached);

        const result = await pool.query("SELECT * FROM ai_config WHERE id = 'default'");
        const row = result.rows[0];

        if (!row) return res.status(404).json({ error: 'No AI config found' });

        // Parse selling_points from JSON string
        try {
            row.selling_points = JSON.parse(row.selling_points || '[]');
        } catch (e) {
            row.selling_points = [];
        }

        setCache('ai-config', row);
        res.json(row);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Update AI config
// Update AI config
app.put('/api/ai-config', authenticateToken, async (req, res) => {
    const { model_name, system_prompt, selling_points, temperature } = req.body;

    const updates = [];
    const values = [];
    let idx = 1;

    if (model_name !== undefined) { updates.push(`model_name = $${idx++}`); values.push(model_name); }
    if (system_prompt !== undefined) { updates.push(`system_prompt = $${idx++}`); values.push(system_prompt); }
    if (selling_points !== undefined) {
        updates.push(`selling_points = $${idx++}`);
        values.push(JSON.stringify(selling_points));
    }
    if (temperature !== undefined) { updates.push(`temperature = $${idx++}`); values.push(temperature); }

    // Always update the timestamp
    updates.push(`updated_at = $${idx++}`);
    values.push(new Date().toISOString());

    if (updates.length === 1) { // Only timestamp
        return res.status(400).json({ error: 'No valid fields to update' });
    }

    values.push('default');
    const query = `UPDATE ai_config SET ${updates.join(', ')} WHERE id = $${idx}`;

    try {
        const result = await pool.query(query, values);
        invalidateCache('ai-config');
        res.json({ success: true, updated: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// --- API Routes for Knowledgebase ---

// Get all knowledgebase entries
app.get('/api/knowledgebase', async (req, res) => {
    try {
        const result = await pool.query("SELECT * FROM knowledgebase ORDER BY category, title");
        const rows = result.rows || [];

        // Parse tags for each entry
        const entries = rows.map(row => ({
            ...row,
            tags: (() => {
                try {
                    return JSON.parse(row.tags || '[]');
                } catch {
                    return [];
                }
            })()
        }));

        res.json(entries);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Create a new knowledgebase entry
app.post('/api/knowledgebase', async (req, res) => {
    const { category, title, content, tags } = req.body;

    if (!title) {
        return res.status(400).json({ error: 'Title is required' });
    }

    const id = 'kb-' + Date.now();
    const now = new Date().toISOString();
    const tagsJson = JSON.stringify(tags || []);

    try {
        await pool.query(
            "INSERT INTO knowledgebase (id, category, title, content, tags, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7)",
            [id, category || 'general', title, content || '', tagsJson, now, now]
        );
        res.json({
            success: true,
            id,
            category: category || 'general',
            title,
            content: content || '',
            tags: tags || [],
            created_at: now,
            updated_at: now
        });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Update a knowledgebase entry
app.put('/api/knowledgebase/:id', async (req, res) => {
    const { id } = req.params;
    const { category, title, content, tags } = req.body;

    const updates = [];
    const values = [];
    let idx = 1;

    if (category !== undefined) { updates.push(`category = $${idx++}`); values.push(category); }
    if (title !== undefined) { updates.push(`title = $${idx++}`); values.push(title); }
    if (content !== undefined) { updates.push(`content = $${idx++}`); values.push(content); }
    if (tags !== undefined) { updates.push(`tags = $${idx++}`); values.push(JSON.stringify(tags)); }

    updates.push(`updated_at = $${idx++}`);
    values.push(new Date().toISOString());

    if (updates.length === 1) {
        return res.status(400).json({ error: 'No valid fields to update' });
    }

    values.push(id);
    const query = `UPDATE knowledgebase SET ${updates.join(', ')} WHERE id = $${idx}`;

    try {
        const result = await pool.query(query, values);
        res.json({ success: true, updated: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Delete a knowledgebase entry
app.delete('/api/knowledgebase/:id', async (req, res) => {
    const { id } = req.params;
    try {
        const result = await pool.query("DELETE FROM knowledgebase WHERE id = $1", [id]);
        res.json({ success: true, deleted: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// --- API Routes for Image Gallery ---

// Get all gallery images
// Get all gallery images
app.get('/api/gallery', async (req, res) => {
    try {
        const result = await pool.query("SELECT * FROM gallery_images ORDER BY created_at DESC");
        const rows = result.rows || [];

        // Add full URL to each image
        const images = rows.map(row => ({
            ...row,
            // If row.url exists (new way), use it. otherwise fallback (legacy local files)
            url: row.url || `/uploads/gallery/${row.filename}`,
            tags: (() => {
                try {
                    return JSON.parse(row.tags || '[]');
                } catch {
                    return [];
                }
            })()
        }));

        res.json(images);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Upload new gallery image(s)
// Upload new gallery image(s) to Supabase Storage
app.post('/api/gallery/upload', authenticateToken, galleryUpload.array('images'), async (req, res) => {
    if (!req.files || req.files.length === 0) {
        return res.status(400).json({ error: 'No image files provided' });
    }

    const { category, tags } = req.body;
    const now = new Date().toISOString();
    const tagsJson = tags ? (typeof tags === 'string' ? tags : JSON.stringify(tags)) : '[]';

    const uploadedImages = [];

    try {
        for (const file of req.files) {
            // Generate unique filename
            const fileExt = path.extname(file.originalname);
            const fileName = `gal-${Date.now()}-${Math.random().toString(36).substr(2, 5)}${fileExt}`;

            // Upload to Cloudflare R2
            try {
                await r2.send(new PutObjectCommand({
                    Bucket: R2_BUCKET,
                    Key: fileName,
                    Body: file.buffer,
                    ContentType: file.mimetype,
                }));
            } catch (uploadErr) {
                console.error("R2 Upload Error:", uploadErr);
                continue; // Skip failed upload
            }

            const publicUrl = `${R2_PUBLIC_URL}/${fileName}`;

            // Save metadata to Database
            const id = 'gal-' + Date.now() + '-' + Math.random().toString(36).substr(2, 5); // DB ID

            await pool.query(
                "INSERT INTO gallery_images (id, filename, original_name, category, tags, created_at, url) VALUES ($1, $2, $3, $4, $5, $6, $7)",
                [id, fileName, file.originalname, category || 'general', tagsJson, now, publicUrl]
            );

            uploadedImages.push({
                id,
                filename: fileName,
                original_name: file.originalname,
                url: publicUrl,
                category: category || 'general',
                tags: (() => {
                    try { return JSON.parse(tagsJson); } catch { return []; }
                })(),
                created_at: now
            });
        }

        invalidateCache('gallery');
        res.json({
            success: true,
            images: uploadedImages,
            count: uploadedImages.length
        });
    } catch (err) {
        console.error("Gallery Upload Error:", err);
        res.status(500).json({ error: err.message });
    }
});

// Update gallery image metadata
// Update gallery image metadata
app.put('/api/gallery/:id', authenticateToken, async (req, res) => {
    const { id } = req.params;
    const { category, tags } = req.body;

    const updates = [];
    const values = [];
    let idx = 1;

    if (category !== undefined) { updates.push(`category = $${idx++}`); values.push(category); }
    if (tags !== undefined) { updates.push(`tags = $${idx++}`); values.push(JSON.stringify(tags)); }

    if (updates.length === 0) {
        return res.status(400).json({ error: 'No valid fields to update' });
    }

    values.push(id);
    const query = `UPDATE gallery_images SET ${updates.join(', ')} WHERE id = $${idx}`;

    try {
        const result = await pool.query(query, values);
        res.json({ success: true, updated: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Delete gallery image (also removes file from disk)
// Delete gallery image (also removes file from disk)
// Delete gallery image (also removes file from Supabase Storage)
// Already updated deletion logic, just checking header... 
// Wait, I updated it in previous step. 
// I need to target the new signature: app.delete('/api/gallery/:id', async (req, res) => {
app.delete('/api/gallery/:id', authenticateToken, async (req, res) => {
    const { id } = req.params;

    try {
        // First get the filename to delete the file
        const result = await pool.query("SELECT filename FROM gallery_images WHERE id = $1", [id]);
        const row = result.rows[0];

        if (!row) return res.status(404).json({ error: 'Image not found' });

        // Delete from database first
        const deleteResult = await pool.query("DELETE FROM gallery_images WHERE id = $1", [id]);

        // Delete file from Cloudflare R2
        try {
            await r2.send(new DeleteObjectCommand({
                Bucket: R2_BUCKET,
                Key: row.filename,
            }));
        } catch (r2Err) {
            console.error("R2 Deletion Error:", r2Err);
        }

        invalidateCache('gallery');
        res.json({ success: true, deleted: deleteResult.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Get random gallery images (for customer flow)
// Prioritizes: 1) Unused images first, 2) Mix of categories, 3) Respects single-use setting
// Get random gallery images (for customer flow)
// Prioritizes: 1) Unused images first, 2) Mix of categories, 3) Respects single-use setting
app.get('/api/gallery/random', async (req, res) => {
    const count = parseInt(req.query.count) || 3;

    try {
        // Get settings
        const settingsResult = await pool.query("SELECT * FROM gallery_settings WHERE id = 'default'");
        const settings = settingsResult.rows[0] || { allow_multiple_uses: 0 };

        const allowMultiple = settings.allow_multiple_uses === 1;

        // Get all images
        const imagesResult = await pool.query("SELECT * FROM gallery_images");
        const rows = imagesResult.rows || [];

        if (rows.length === 0) return res.json([]);

        // Filter: If single-use mode, exclude already-used images
        let availableImages = allowMultiple ? rows : rows.filter(img => (img.use_count || 0) === 0);

        // If no unused images available in single-use mode, return empty (no fallback)
        if (availableImages.length === 0) {
            return res.json([]);
        }

        // Sort by use_count (least used first), then shuffle within groups
        availableImages.sort((a, b) => {
            const countDiff = (a.use_count || 0) - (b.use_count || 0);
            if (countDiff !== 0) return countDiff;
            return Math.random() - 0.5;
        });

        // Select images with category variety
        const categories = [...new Set(availableImages.map(img => img.category))];
        const selected = [];
        const usedCategories = new Set();

        // First pass: pick one from each category (prioritizing unused)
        for (const category of categories) {
            if (selected.length >= count) break;
            const catImages = availableImages.filter(img => img.category === category && !selected.find(s => s.id === img.id));
            if (catImages.length > 0) {
                selected.push(catImages[0]);
                usedCategories.add(category);
            }
        }

        // Second pass: fill remaining slots with any unused images
        for (const img of availableImages) {
            if (selected.length >= count) break;
            if (!selected.find(s => s.id === img.id)) {
                selected.push(img);
            }
        }

        // Format response
        const result = selected.map(row => ({
            ...row,
            // Use stored Supabase URL or fallback to local (legacy)
            url: row.url || `/uploads/gallery/${row.filename}`,
            tags: (() => {
                try {
                    return JSON.parse(row.tags || '[]');
                } catch {
                    return [];
                }
            })()
        }));

        res.json(result);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Increment use count for gallery images (called when used in review)
app.post('/api/gallery/use', async (req, res) => {
    const { imageIds } = req.body;

    if (!imageIds || !Array.isArray(imageIds) || imageIds.length === 0) {
        return res.status(400).json({ error: 'imageIds array is required' });
    }

    const placeholders = imageIds.map((_, i) => `$${i + 1}`).join(',');

    try {
        const result = await pool.query(
            `UPDATE gallery_images SET use_count = use_count + 1 WHERE id IN (${placeholders})`,
            imageIds
        );
        invalidateCache('gallery');
        res.json({ success: true, updated: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Reset use count for a single image or all images
app.post('/api/gallery/reset-count', async (req, res) => {
    const { imageId } = req.body;

    try {
        let result;
        if (imageId) {
            // Reset single image
            result = await pool.query("UPDATE gallery_images SET use_count = 0 WHERE id = $1", [imageId]);
        } else {
            // Reset all images
            result = await pool.query("UPDATE gallery_images SET use_count = 0");
        }
        invalidateCache('gallery');
        res.json({ success: true, updated: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Get gallery settings
app.get('/api/gallery/settings', async (req, res) => {
    try {
        const result = await pool.query("SELECT * FROM gallery_settings WHERE id = 'default'");
        res.json(result.rows[0] || { allow_multiple_uses: 0 });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Update gallery settings
// Update gallery settings
app.put('/api/gallery/settings', authenticateToken, async (req, res) => {
    const { allow_multiple_uses } = req.body;
    const now = new Date().toISOString();

    try {
        await pool.query(
            "UPDATE gallery_settings SET allow_multiple_uses = $1, updated_at = $2 WHERE id = 'default'",
            [allow_multiple_uses ? 1 : 0, now]
        );
        invalidateCache('gallery');
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Get gallery status (for admin alerts) (cached)
app.get('/api/gallery/status', async (req, res) => {
    try {
        const cached = getCached('gallery-status');
        if (cached) return res.json(cached);

        // Get settings
        const settingsResult = await pool.query("SELECT * FROM gallery_settings WHERE id = 'default'");
        const settings = settingsResult.rows[0] || { allow_multiple_uses: 0 };

        // Get image counts
        const countsResult = await pool.query(`
            SELECT
                COUNT(*) as total,
                SUM(CASE WHEN use_count = 0 OR use_count IS NULL THEN 1 ELSE 0 END) as unused
            FROM gallery_images
        `);
        const counts = countsResult.rows[0] || { total: 0, unused: 0 };

        const total = parseInt(counts.total);
        const unused = parseInt(counts.unused);

        const isDepleted = settings.allow_multiple_uses === 0 && unused === 0 && total > 0;

        const data = {
            totalImages: total,
            unusedImages: unused,
            allowMultipleUses: settings.allow_multiple_uses === 1,
            isDepleted
        };
        setCache('gallery-status', data);
        res.json(data);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});


// --- Authentication Routes ---

app.post('/api/auth/login', async (req, res) => {
    const { username, password } = req.body;
    try {
        const result = await pool.query("SELECT * FROM users WHERE username = $1 AND password = $2", [username, password]);
        const row = result.rows[0];

        if (!row) return res.status(401).json({ error: "Invalid credentials" });

        // In producton, sign a JWT. Here, return simple user object.
        res.json({ success: true, user: { id: row.id, username: row.username, role: row.role, profile_pic: row.profile_pic }, token: "mock-token-" + row.id });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.post('/api/auth/register', async (req, res) => {
    const { username, password, role } = req.body;
    const validRoles = ['staff', 'manager', 'admin'];
    const userRole = validRoles.includes(role) ? role : 'staff';
    const id = `user-${Date.now()}`;

    try {
        await pool.query("INSERT INTO users (id, username, password, role) VALUES ($1, $2, $3, $4)", [id, username, password, userRole]);
        res.json({ success: true, id, role: userRole });
    } catch (err) {
        return res.status(500).json({ error: "Username already exists or DB error: " + err.message });
    }
});

// Get all users (for admin panel)
// Get all users (for admin panel)
// Get all users (for admin panel)
app.get('/api/users', authenticateToken, async (req, res) => {
    try {
        const result = await pool.query("SELECT id, username, role, profile_pic FROM users ORDER BY username");
        res.json(result.rows || []);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Delete a user
// Delete a user
app.delete('/api/users/:id', authenticateToken, async (req, res) => {
    const { id } = req.params;
    try {
        const result = await pool.query("DELETE FROM users WHERE id = $1", [id]);
        res.json({ success: true, deleted: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Update a user
// Update a user
app.put('/api/users/:id', authenticateToken, async (req, res) => {
    const { id } = req.params;
    const { username, password, role, profile_pic } = req.body;

    // Build dynamic update query based on provided fields
    const updates = [];
    const values = [];
    let idx = 1;

    if (username) {
        updates.push(`username = $${idx++}`);
        values.push(username);
    }
    if (password) {
        updates.push(`password = $${idx++}`);
        values.push(password);
    }
    if (role) {
        const validRoles = ['staff', 'manager', 'admin'];
        if (validRoles.includes(role)) {
            updates.push(`role = $${idx++}`);
            values.push(role);
        }
    }
    if (profile_pic !== undefined) {
        updates.push(`profile_pic = $${idx++}`);
        values.push(profile_pic);
    }

    if (updates.length === 0) {
        return res.status(400).json({ error: 'No valid fields to update' });
    }

    values.push(id);
    const query = `UPDATE users SET ${updates.join(', ')} WHERE id = $${idx}`;

    try {
        const result = await pool.query(query, values);
        res.json({ success: true, updated: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// --- API Routes for Dashboard ---

// Track QR Scan (Visit)
// Track QR Scan (Visit)
app.post('/api/scan', async (req, res) => {
    const { branchId } = req.body;
    const id = `visit-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

    try {
        await pool.query("INSERT INTO visits (id, branchId, timestamp) VALUES ($1, $2, $3)", [id, branchId || 'main', Date.now()]);
        res.json({ success: true, id });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Get Dashboard Analytics (Aggregated) — consolidated into 2 queries (was 6)
app.get('/api/dashboard/stats', async (req, res) => {
    const { period } = req.query; // 'today', 'week', 'month', 'all'

    let timeFilter = 0;
    const now = Date.now();
    const DAY = 24 * 60 * 60 * 1000;

    if (period === 'today') {
        const startOfDay = new Date().setHours(0, 0, 0, 0);
        timeFilter = startOfDay;
    } else if (period === 'week') {
        timeFilter = now - (7 * DAY);
    } else if (period === 'month') {
        timeFilter = now - (30 * DAY);
    }

    const cacheKey = `stats-${period || 'all'}`;
    const cached = getCached(cacheKey);
    if (cached) return res.json(cached);

    try {
        // Single query for all submission stats + platform data (was 5 separate queries)
        const [visitsResult, subsResult] = await Promise.all([
            pool.query(`SELECT COUNT(*) as count FROM visits WHERE timestamp >= $1`, [timeFilter]),
            pool.query(`SELECT COUNT(*) as total, COUNT(CASE WHEN status = 'Verified' THEN 1 END) as verified, AVG(rating) as avg_rating, GROUP_CONCAT(platformsSelected, '|||') as platforms FROM submissions WHERE timestamp >= $1`, [timeFilter])
        ]);

        const subRow = subsResult.rows[0] || {};
        const platformCounts = {};
        const platformsRaw = subRow.platforms;
        if (platformsRaw) {
            platformsRaw.split('|||').forEach(platformsJson => {
                if (!platformsJson) return;
                try {
                    const platforms = JSON.parse(platformsJson);
                    platforms.forEach(p => platformCounts[p] = (platformCounts[p] || 0) + 1);
                } catch (e) { }
            });
        }

        const stats = {
            visits: parseInt(visitsResult.rows[0]?.count || 0),
            totalReviews: parseInt(subRow.total || 0),
            avgRating: parseFloat(subRow.avg_rating || 0),
            verifiedReviews: parseInt(subRow.verified || 0),
            platforms: platformCounts
        };

        setCache(cacheKey, stats);
        res.json(stats);

    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Get all submissions (for dashboard)
// Proofs are stripped from the list to save egress — use GET /api/submissions/:id/proofs for individual proofs
app.get('/api/submissions', async (req, res) => {
    try {
        const result = await pool.query(`
            SELECT
                s.id, s.customerName, s.branchId, s.staffId, s.therapistId,
                s.products, s.highlights, s.rating, s.feedback,
                s.platformsSelected, s.status, s.timestamp,
                s.rewardClaimed, s.luckyDrawTicket, s.phone, s.bonusEntries,
                s.proofs,
                st.name as "staffName",
                th.name as "therapistName"
            FROM submissions s
            LEFT JOIN staff st ON s.staffId = st.id
            LEFT JOIN staff th ON s.therapistId = th.id
            ORDER BY s.timestamp DESC
        `);

        const submissions = result.rows.map(row => {
            // Parse proofs but strip base64 content — only keep metadata
            let proofsMeta = [];
            try {
                const rawProofs = JSON.parse(row.proofs || '[]');
                proofsMeta = rawProofs.map(p => ({
                    platform: p.platform,
                    type: p.type,
                    // For links keep the URL; for images just indicate one exists
                    content: p.type === 'link' ? p.content : '[image]',
                    hasImage: p.type === 'image' && !!p.content,
                    timestamp: p.timestamp
                }));
            } catch (e) { }

            return {
                id: row.id,
                branchId: row.branchid || row.branchId,
                staffId: row.staffid || row.staffId,
                therapistId: row.therapistid || row.therapistId,
                phone: row.phone,
                customerName: row.customername || row.customerName || 'Unknown Customer',
                products: JSON.parse(row.products || '[]'),
                highlights: JSON.parse(row.highlights || '[]'),
                platformsSelected: JSON.parse(row.platformsselected || row.platformsSelected || '[]'),
                proofs: proofsMeta,
                rating: row.rating,
                feedback: row.feedback,
                status: row.status,
                timestamp: row.timestamp,
                rewardClaimed: !!(row.rewardClaimed ?? row.rewardclaimed),
                staffName: row.staffName || row.staffname || 'Unknown',
                therapistName: row.therapistName || row.therapistname || 'Unknown',
                luckyDrawTicket: row.luckydrawticket || row.luckyDrawTicket,
                bonusEntries: row.bonusentries || row.bonusEntries || 0
            };
        });
        res.json({ submissions });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Get proofs for a single submission (lazy-loaded by dashboard when viewing)
app.get('/api/submissions/:id/proofs', async (req, res) => {
    const { id } = req.params;
    try {
        const result = await pool.query("SELECT proofs FROM submissions WHERE id = $1", [id]);
        const row = result.rows[0];
        if (!row) return res.status(404).json({ error: 'Submission not found' });

        const proofs = JSON.parse(row.proofs || '[]');
        res.json({ proofs });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Upload proofs separately (to avoid Vercel body size limit)
app.put('/api/submissions/:id/proofs', async (req, res) => {
    const { id } = req.params;
    const { proofs } = req.body;
    try {
        await pool.query("UPDATE submissions SET proofs = $1 WHERE id = $2", [JSON.stringify(proofs || []), id]);
        res.json({ success: true });
    } catch (err) {
        console.error("Proof upload error:", err);
        res.status(500).json({ error: err.message });
    }
});

// Add new submission (from Customer App)
app.post('/api/submissions', async (req, res) => {
    const sub = req.body;

    try {
        await pool.query(`
    INSERT INTO submissions (
      id, customerName, branchId, staffId, therapistId, 
      products, highlights, rating, feedback, platformsSelected, 
      proofs, status, timestamp, rewardClaimed, luckyDrawTicket, phone, bonusEntries
    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
  `, [
            sub.id,
            sub.customerName || '',
            sub.branchId,
            sub.staffId || null,
            sub.therapistId || null,
            JSON.stringify(sub.products || []),
            JSON.stringify(sub.highlights || []),
            sub.rating,
            sub.feedback || '',
            JSON.stringify(sub.platformsSelected || []),
            JSON.stringify(sub.proofs || []),
            sub.status,
            sub.timestamp,
            sub.rewardClaimed ? 1 : 0,
            sub.luckyDrawTicket || null,
            sub.phone || '',
            sub.bonusEntries || 0
        ]);

        invalidateCache('stats');
        res.json({ success: true, id: sub.id });
    } catch (err) {
        console.error("Insert Error:", err);
        res.status(500).json({ error: err.message });
    }
});

// Update submission (Status, Phone, etc)
app.patch('/api/submissions/:id', async (req, res) => {
    const { status, phone, feedback } = req.body;
    const { id } = req.params;

    // Dynamic query construction
    const updates = [];
    const values = [];
    let idx = 1;

    if (status) { updates.push(`status = $${idx++}`); values.push(status); }
    if (phone) { updates.push(`phone = $${idx++}`); values.push(phone); }
    if (feedback) { updates.push(`feedback = $${idx++}`); values.push(feedback); }

    if (updates.length === 0) return res.json({ success: true, message: "No updates" });

    values.push(id);

    const sql = `UPDATE submissions SET ${updates.join(", ")} WHERE id = $${idx}`;

    try {
        const result = await pool.query(sql, values);
        invalidateCache('stats');
        res.json({ success: true, changes: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// --- Admin Routes ---
// --- Admin Routes ---
// --- Admin Routes ---
// --- Admin Routes ---

// Get Branches (cached)
app.get('/api/branches', async (req, res) => {
    try {
        const cached = getCached('branches');
        if (cached) return res.json(cached);

        const result = await pool.query("SELECT * FROM branches ORDER BY id");
        const data = result.rows || [];
        setCache('branches', data);
        res.json(data);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Update Branch Name
app.put('/api/branches/:id', authenticateToken, async (req, res) => {
    const { id } = req.params;
    const { name } = req.body;
    try {
        await pool.query("UPDATE branches SET name = $1 WHERE id = $2", [name, id]);
        invalidateCache('branches');
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Delete Branch
app.delete('/api/branches/:id', authenticateToken, async (req, res) => {
    const { id } = req.params;
    try {
        const result = await pool.query("DELETE FROM branches WHERE id = $1", [id]);
        invalidateCache('branches');
        res.json({ success: true, deleted: result.rowCount });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Clear All Data (Submissions & Visits)
app.post('/api/admin/clear-data', authenticateToken, async (req, res) => {
    try {
        // Using DELETE FROM for simplicity and safety across DB versions/configs
        await pool.query("DELETE FROM submissions");
        await pool.query("DELETE FROM visits");

        console.log(`Data cleared by user ${req.user?.username}`);
        res.json({ success: true });
    } catch (err) {
        console.error("Error clearing data:", err);
        res.status(500).json({ error: err.message });
    }
});

// --- Staff Management ---

// Get All Staff (cached)
app.get('/api/staff', async (req, res) => {
    try {
        const cached = getCached('staff');
        if (cached) return res.json(cached);

        const result = await pool.query("SELECT * FROM staff ORDER BY name");
        const data = result.rows || [];
        setCache('staff', data);
        res.json(data);
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Add Staff
app.post('/api/staff', authenticateToken, async (req, res) => {
    const { name, role, branchId } = req.body;
    const id = `s-${Date.now()}`;
    try {
        await pool.query("INSERT INTO staff (id, name, role, branch_id) VALUES ($1, $2, $3, $4)", [id, name, role, branchId]);
        invalidateCache('staff');
        res.json({ success: true, id });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Update Staff
app.put('/api/staff/:id', authenticateToken, async (req, res) => {
    const { id } = req.params;
    const { name, role, branchId } = req.body;
    try {
        await pool.query("UPDATE staff SET name = $1, role = $2, branch_id = $3 WHERE id = $4", [name, role, branchId, id]);
        invalidateCache('staff');
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

// Delete Staff
app.delete('/api/staff/:id', authenticateToken, async (req, res) => {
    const { id } = req.params;
    try {
        await pool.query("DELETE FROM staff WHERE id = $1", [id]);
        invalidateCache('staff');
        res.json({ success: true });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.post('/api/admin/clear-data', authenticateToken, async (req, res) => {
    // In production, verify admin token here
    console.log("Admin initiated Clear Data...");
    try {
        const subResult = await pool.query("DELETE FROM submissions");
        console.log("Submissions cleared. Rows:", subResult.rowCount);

        const visitResult = await pool.query("DELETE FROM visits");
        console.log("Visits cleared. Rows:", visitResult.rowCount);

        res.json({ success: true, message: "All data cleared." });
    } catch (err) {
        console.error("Error clearing data:", err);
        res.status(500).json({ error: err.message });
    }
});

// --- Production: Serve Static Frontend ---
// Serve built Vite files from dist folder
app.use(express.static(path.join(__dirname, 'dist')));

// SPA fallback: serve index.html for all non-API routes
app.get(/(.*)/, (req, res) => {
    res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

// Start server only when run directly (not imported by Vercel)
if (process.env.VERCEL !== '1') {
    app.listen(PORT, () => {
        console.log(`Server running on port ${PORT}`);
    });
}

export default app;
